### ISSUE TITLE
nvim-dap-ui config, missing function wrapper around call to `require("dapui").close()`

### ISSUE THREAD

**Issue by meuter** [chrisgrieser/nvim-kickstart-python#1]
Hey,

[I am coming from your reddit post] I was browsing through the code, and I spotted something fishy. I am not 100% sure, but I think there might be a problem with the `nvim-dap-ui` config. Specifically the part when you setup the event handlers:

```
config = function()
			local listener = require("dap").listeners
			listener.after.event_initialized["dapui_config"] = function() require("dapui").open() end
			listener.before.event_terminated["dapui_config"] = require("dapui").close()
			listener.before.event_exited["dapui_config"] = require("dapui").close()
		end,
```

for `event_terminated` and `event_exited`, you call the `close()` function directly (so at config-time, not when the event is actually fired). I think what you want is:

```
listener.before.event_terminated["dapui_config"] = function() require("dapui").close() end
listener.before.event_exited["dapui_config"] = function() require("dapui").close() end
```

Anyway, I thought I'd mention it ;-)

**Comment by chrisgrieser** [comment]
you are completely right, was a copypaste-mistake 😅 

Thanks!
