### ISSUE TITLE
Add error handling to the lazy plugin manager bootstrap

### ISSUE THREAD

**Issue by jpoliv** [chrisgrieser/nvim-kickstart-python#3]
Please consider picking the following Folke's commit that adds error handling to the plugin manager bootstrap.

Kickstart.nvim commit:
 * https://github.com/nvim-lua/kickstart.nvim/commit/3e55ff1a83dc7a9813d8f2220cefd90b07aacdab

Notes
* the commit has been merged to the kickstart.nvim project via the pull request [1001](https://github.com/nvim-lua/kickstart.nvim/pull/1001)
 * Folke's also suggests a "prettier" alternative on the [pull](https://github.com/nvim-lua/kickstart.nvim/pull/1001) request description

**Comment by chrisgrieser** [comment]
If you have identified a problem and also have the solution ready, why aren't you making a PR?
