### ISSUE TITLE
ruff-lsp has been deprecated in favor of ruff server

### ISSUE THREAD

**Issue by jpoliv** [chrisgrieser/nvim-kickstart-python#4]
The ruff-lsp has been deprecated in favor of ruff server shipped in ruff 0.5.3.

ruff-lsp deprecation note:
 * https://github.com/astral-sh/ruff-lsp
 
ruff 0.5.3 release notes (ruff server tagged as stable):
 * https://github.com/astral-sh/ruff/releases/tag/0.5.3

ruff server documentation:
 * Editor integration: https://docs.astral.sh/ruff/editors
 * Setup: https://docs.astral.sh/ruff/editors/setup/
 * Neovim setup: https://docs.astral.sh/ruff/editors/setup/#neovim
 * Migration from ruff-lsp: https://docs.astral.sh/ruff/editors/migration/
 
 Blog post:
  * The ruff language server: https://astral.sh/blog/ruff-v0.4.5

**Comment by chrisgrieser** [comment]
PRs are welcome
