### ISSUE TITLE
New version of venv-select (on branch regexp)

### ISSUE THREAD

**Issue by jpoliv** [chrisgrieser/nvim-kickstart-python#8]
Starting neovim with the current configuration file (nvim -u kickstart-python.lua) produces the following messages:
----
VenvSelect: This plugin has a new 2024 version that was rewritten from scratch to support user defined searches: https://github.com/linux-cultist/venv-selector.nvim/tree/regexp.
VenvSelect: Its highly recommended to upgrade, but if you want to stay on this version, you can set the option 'stay_on_this_version' to true. Only the new version will receive updates.
----

Message on the plugin site:
https://github.com/linux-cultist/venv-selector.nvim/tree/main?tab=readme-ov-file#2024-05-14---new-version-of-venvselect

Regexp branch:
https://github.com/linux-cultist/venv-selector.nvim/tree/regexp

New configuration snippet:
https://github.com/linux-cultist/venv-selector.nvim/tree/regexp#configuration-snippet-for-lazynvim

Neovim version used:
* 0.10.0

**Comment by chrisgrieser** [comment]
Again, if you have the fix, why don't you do a PR?
